# Generated by Django 4.1 on 2022-08-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=10)),
                ("profilePic", models.ImageField(upload_to="")),
                ("tags", models.CharField(max_length=10)),
            ],
        ),
    ]
