# Generated by Django 4.1 on 2022-09-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment_alter_post_id_delete_answer_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
