# Generated by Django 4.1 on 2022-09-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_post_date_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
